[[constraint]]
  name = "github.com/go-redis/redis"
  version = "~6.9.2"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "~1.0.0"

[[constraint]]
  name = "github.com/grpc-ecosystem/go-grpc-prometheus"
  branch = "master"

[[constraint]]
  name = "github.com/op/go-logging"
  branch = "master"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  branch = "master"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "~1.0.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "~1.2.1"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "~1.20.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "~1.10.0"

[prune]
  go-tests = true
  unused-packages = true
